name = "ubiquity-os-command-query-user"
main = "src/index.ts"
compatibility_date = "2024-09-24"
compatibility_flags = [ "nodejs_compat" ]
[env.dev]
[env.prod]
[observability]
enabled = true

[version_metadata]
binding = "CLOUDFLARE_VERSION_METADATA"